# Generated by Django 2.2.2 on 2019-07-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruser',
            name='cooperative_actions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playeruser',
            name='cooperative_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='playeruser',
            name='games_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playeruser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
