# Generated by Django 2.2.2 on 2019-10-10 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190703_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='name of the game')),
                ('round', models.IntegerField(default=1, verbose_name='current round of the game')),
                ('player_one_action', models.CharField(choices=[('COOP', 'COOPERATE'), ('SELF', 'NOT COOPERATE'), ('NONE', 'AWAITING ACTION')], default='NONE', max_length=4, verbose_name="player one's action this round")),
                ('player_two_action', models.CharField(choices=[('COOP', 'COOPERATE'), ('SELF', 'NOT COOPERATE'), ('NONE', 'AWAITING ACTION')], default='NONE', max_length=4, verbose_name="player two's action this round")),
                ('player_one_points', models.IntegerField(default=0, verbose_name='points player one has earned')),
                ('player_two_points', models.IntegerField(default=0, verbose_name='points player two has earned')),
                ('player_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='player one')),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='player two')),
            ],
        ),
    ]
