# Generated by Django 2.2.2 on 2019-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_one_coop',
            field=models.IntegerField(default=0, verbose_name="player one's cooperative actions this game"),
        ),
        migrations.AddField(
            model_name='game',
            name='player_two_coop',
            field=models.IntegerField(default=0, verbose_name="player two's cooperative actions this game"),
        ),
    ]
