# Generated by Django 2.2.2 on 2019-11-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191028_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_player_one_unregistered',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_player_two_unregistered',
        ),
        migrations.AddField(
            model_name='game',
            name='is_player_one_present',
            field=models.BooleanField(default=False, verbose_name='Is there an unregistered player one'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_player_two_present',
            field=models.BooleanField(default=False, verbose_name='Is there an unregistered player two'),
        ),
    ]
